name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: python3 mbs/mbs
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: targets/jonchki/repository/**
